### ISSUE TITLE
What the license of the data?

### ISSUE THREAD

**Issue by mdom** [rsek/dataforged#24]
And thanks for all the work!

Cheers, Mario

**Comment by rsek** [comment]
i've updated the readme to clarify the licensing (thanks for the reminder there btw, it'd slipped my mind!). the short version is: it'll be some flavour of CC once the final game is released (paralleling _Ironsworn_ and _Ironsworn: Delve_), but for now it's intended for private use, mostly so that unfinished versions of the rules aren't being widely circulated (and so that the backer preview retains some value for the KS backers).

**that said**, the whole point of this repo is to make things easier for people who want to develop community tools! and it's pretty hard to develop those without actually sharing them with the community. (eventually it should be fine to just pull the data directly from the repo, but i want to give the json structure a little time to settle before i go recommending that).

so, as long as you're not reselling or repackaging them as your own work, you're probably in the clear; it's to everyone's benefit if there's more cool Starforged tools out there in the world, and being really strict about constitutes "private use" would get in the way of that. that said, i can't imagine _every_ possible use of the data, so if you're not sure, my recommendation is to ask Shawn Tomkin himself on the [official Ironsworn Discord](https://discordapp.com/invite/6QMvmJb).

i'll leave this issue open for a few days in case there's any more questions.

**Comment by mdom** [comment]
Thanks for explanation and the quick update. I'llust develop my app in a private repository until the official release then. And thanks for the great work. I'm so happy that i don't have to copy, paste and clean all the data!
