### ISSUE TITLE
2 Missing Move Oracles

### ISSUE THREAD

**Issue by nboughton** [rsek/dataforged#32]
The following Move Oracle data appears to be missing, i.e referenced in the Move data but without a corresponding entry in oracles/moves.json:

Begin a Session
Ask the Oracle

**Comment by rsek** [comment]
Ask the Oracle is in its own category cuz it sometimes gets implemented differently (it's sort of a weird table). but this was a pretty arbitrary decision on my part, hah - i'll combine it into a single entry in the Moves category.

begin a session probably isn't present because `oracles/move.json` hasn't been updated in a bit (check out the `Date` key). the main reason they're still there is, uh, i forgot to delete them 😅 ; consider it (and all other single-category oracle files) deprecated. my recommendation is to use `oracles.json` instead, which retains the category groupings - it's identical to dumping every oracle category object into a single array. which is what most people seemed to be doing anyways.
