### ISSUE TITLE
Assets missing Impact fields

### ISSUE THREAD

**Issue by vagueGM** [rsek/dataforged#33]
- **Vehicles** should have the '**Battered**' condition checkbox to represent Vehicle Troubles
- **Command Vehicle** (Starship) should also have the '**Cursed**' condition.
- **Companions** should have the '**Out of Action**' condition.
- **Modules** _might_ need the '**Broken**' condition, but it is not listed on the Assets cards. It feels like a different thing and might not be relevant here nor need the same treatment.

I don't know how they should be formatted in the json (so no pull request), a boolean seems wrong, but could represent a 'checkbox'?

**Comment by rsek** [comment]
good idea. my instinct would be to implement them as a key of `Condition Meter`, probably an array of strings:

```
"Condition Meter": {
  "Name": "Integrity",
  "Max": 5,
  "Conditions": ["Battered", "Cursed"]
}
```

broken modules is an interesting case. it'd definitely be good to have a place to track them. i'll pass a suggestion to add those to the cards "upstream" to shawn and see what he says.

**Comment by vagueGM** [comment]
That looks like a good place to put it.

Some of these are 'Impacts' some are only conditions on the asset. I don't think we need to differentiate them in the data, it is pretty clear from the context.

I have added these to my markdown notes and can easily port them to the json, do you want me to make a pull request? Where is best to add them, I am not clear on which files is the master source.

**Comment by rsek** [comment]
> I have added these to my markdown notes and can easily port them to the json, do you want me to make a pull request? Where is best to add them, I am not clear on which files is the master source.

the loose YAML files in `_data-master` are the masters. **however**, a straightforward conversion to JSON won't really work, as that YAML has several idiosyncracies that exist purely to make reading/editing them less onerous for me (2d arrays for tables, aliases shared by multiple files, etc). to get the JSON you see in the repo's root directory, the YAML files are composed/transformed by a local Node script that is not on the repo (partly because it's very ugly and i don't want to commit it posterity, partly because putting it online would mean i have to support it, and partly because there hasn't been a ton of interest in PRs).

at some point i ought to clean that thing up - or simply move to JSON masters once Starforged is actually finished - but for the time being it's much more expedient to just do it myself.

put another way, composing a post explaining all that took much longer (by a couple orders of magnitude) than just doing the edits and running the script. ;) thanks for the offer, regardless!

**Comment by rsek** [comment]
resolved in #43e8dfdb9a62b2495949a0c893bb9ed890507c3f

**Comment by vagueGM** [comment]
The book uses "Out of Action" for Companions, "Wounded" is a PC Impact.
It probably does not matter too much, but might confuse things, especially since nearly half of them are bots, and 'wounded' does not really fit with a bot. :)

The rest look good.

**Comment by vagueGM** [comment]
See, your laptop (companion asset) is 'out of action' not 'wounded'. :)
Anyway, my batteries are strong! Pull request added.

**Comment by rsek** [comment]
thanks, looks good!
