### ISSUE TITLE
Planetary description data missing in Planets oracle

### ISSUE THREAD

**Issue by nboughton** [rsek/dataforged#50]
I might just have missed it but I can't find the default descriptions for the different planet types in the Planets oracles. I.e; for Desert: "A pitiless planet of searing heat, blowing sand, and sunbaked rock." and so on.

**Comment by rsek** [comment]
for the planetary class oracle (`$id: "Oracles / Planets / Class"`) itself, that change is intentional - the table is presented without them in the book, so i decided to remove them.

however, they *should* still be available as the `Description` key of the planet category oracles (e.g. `$id: "Oracles / Planets / Furnace`)... but for some reason they're not being included when i build them from templates. i probably just missed them when i was refactoring - i'll take a look and correct that.

**Comment by rsek** [comment]
also, i've been thinking on adding a key for references to oracle categories - one separate from the key for oracle *rolls*. basically, i reckon there's a different sort of operation implied by ">Stellar Object" (which i'd infer to mean "turn to the stellar object oracle and roll on it, 'cause it's just one table") vs ">Furnace World" (which i'd infer to mean "turn to the furnace world category and consider whether you want to roll more oracles") ... but the text itself doesn't make a distinction between the two, because in the context of the book, the little arrows are really just a marker for "this is a jump link".

anyways. if you want to include the description of the planetary class with the table in stargazer (or something else like a popover 'preview'?), maybe that pointer would be helpful?

**Comment by rsek** [comment]
fixed in 32d230a . i'll open a separate issue re: adding a key for references to other oracle categories.
