### ISSUE TITLE
Query: Is Ironsworn data going to move in here as well?

### ISSUE THREAD

**Issue by mtwomey** [rsek/dataforged#65]
I like the format you're using for data here better than datasworn. Especially things like links in the moves markdown. I see that much of the Ironsworn data is also here and it appears like this might be the primary location for both? (e.g. lots of commits / updates here, not so much on datasworn).

**Comment by rsek** [comment]
the plan is to update datasworn with the new format and then distribute it as its own npm package; for the moment the new data is here mainly to make it easier to distribute with the dataforged npm package for testing.

my rationale there is: since datasworn isnt packaged, making breaking changes is a bit riskier. and when i do package it, id like it to be fairly complete (content-wise) so folks can migrate and still access the equivalent data.

see also #47 for progress updates

**Comment by mtwomey** [comment]
Ok - thanks sir. I'm pulling Ironsworn from here for now, but I'll keep in mind that this may go away and / or change. Appreciate the info. Right now I'm still just using the raw json, but looking forward to the packaged version.

**Comment by rsek** [comment]
> Ok - thanks sir. I'm pulling Ironsworn from here for now, but I'll keep in mind that this may go away and / or change. Appreciate the info. Right now I'm still just using the raw json, but looking forward to the packaged version.

oh, the dataforged package includes WIP ironsworn data to make it easier for people to test, it's just not documented in the readme:

```javascript
import { ironsworn } from 'dataforged'
```

that will give you the type annotations and such, too :)

**Comment by mtwomey** [comment]
Oh - nice! Ok, thanks.

**Comment by mtwomey** [comment]
Oh man, the module is so much easier to use. Awesome.
